### ISSUE TITLE
Issue: possible issue in jamfpro_policy with import function ?

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#635]
Hi,

I'm trying to use the terraform `import` function with policies.
For policies with Self Service enabled `terraform plan` says that the resources will be **updated in-place** instead of **imported**.

Here is an example:

```
  # module.policies["771149E1-AEB0-4F35-BBE1-97CE52ED2212"].jamfpro_policy.object will be updated in-place
  # (imported from "12")
  ~ resource "jamfpro_policy" "object" {
        category_id                   = 5
        enabled                       = true
[...]
      + self_service {
          + feature_on_main_page            = true
          + force_users_to_view_description = true
          + install_button_text             = "Exécuter"
          + reinstall_button_text           = "Exécuter"
          + self_service_display_name       = "Réparation de votre Mac"
          + self_service_icon_id            = (known after apply)
          + use_for_self_service            = true

          + self_service_category {
              + display_in = true
              + feature_in = true
              + id         = 5
            }
        }
[...]
```

As you can see in the example above, the `self_service` block is created despite the fact that it already exists in the Jamf Pro server, with the exact same values.

Perhaps I'm doing something wrong but I don't encounter this behaviour on other resources for imports.
May be this is related to the `icon` attribute? As it is (re)created, it impacts the whole `self_service` block?

Thanks for helping!
Emmanuel

**Comment by thejoeker12** [comment]
Reviewing this!

**Comment by thejoeker12** [comment]
Are you trying to import an existing block or use --generate-config-out to make one?

**Comment by ecanault** [comment]
Import from scratch: the resource is not existing yet in the plan.
I don't use the `--generate-config-out` option.

**Comment by ecanault** [comment]
Here is a sample for one policy; each policy is "stored" under its own UUID to identify them uniquely.

```
  079DCAD2-95A4-4563-8BEF-F08A153B47CC:
    # Jamf Pro ID (optional)
    import_id: 27

    # Display Name
    policy_name: p_install_3CX_Desktop

    # Enabled
    policy_enabled: true

    # Site
    policy_site: None

    # Category
    policy_category: Applications

    # Trigger
    policy_trigger_startup: false  
    policy_trigger_login: false
    policy_trigger_network_change: false
    policy_trigger_enrollment: false
    policy_trigger_checkin: false
    policy_trigger_custom:

    # Execution Frequency
    policy_frequency: Ongoing

    # Automatically re-run policy on failure
    policy_offline: false

    # Retry Event
    policy_retry_event:

    # Retry Attempts
    policy_retry_attempts: -1

    # Send notifications for each failed policy retry
    policy_retry_notify:

    # Payloads
    policy_payloads:

      # Packages
      packages:
        - name: 3CX Desktop App.pkg
          action: Install
          fut:
          feu:

      # Scripts
      scripts: []

      # Printers
      printers: []

      # Dock Items
      dock_items: []

      # Local Accounts
      local_accounts: []

      # Management Accounts
      management_accounts:

      # Restart Options
      restart:
        startup_disk: Current Startup Disk
        local_startup_disk:
        no_user_logged_in_action: Do not restart
        user_logged_in_action: Do not restart
        authenticated_restart: false
        delay: 5
        delay_timer: false
        restart_message: This computer will restart in 5 minutes. Please save anything you are working on and log out by choosing Log Out from the bottom of the Apple menu.

      # Maintenance
      maintenance:
        update_inventory: true
        reset_computer_name: false
        install_cached_packages: false
        fix_byhost_preferences: false
        flush_system_cache: false
        flush_user_cache: false
        verify_startup_disk: false

      # Files and Processes
      files_processes:

    # Scope
    policy_scope:

      # Targets
      all_computers: true
      all_users: false
      computer_groups: []
      buildings: []
      departments: []

      # Limitations
      limitations:
        network_segments: []
        directory_user_groups: []

      # Exclusions
      exclusions:
        computer_groups: []
        buildings: []
        departments: []
        network_segments: []
        directory_user_groups: []

    # Self Service
    policy_self_service:

      # Make the policy available in Self Service
      enabled: true

      # Self Service Display Name
      name: 3CX Desktop

      # Button Name Before Initiation
      install_button_name: Install

      # Button Name After Initiation
      reinstall_button_name: Reinstall

      # Description
      description:

      # Ensure that users view the description
      force_view_description:

      # Include the policy in the Featured category
      display_in_featured:

      # Categories
      categories:
        - name: Applications
          display_in: true
          feature_in: true

    # User Interaction
    policy_user_interaction:
```

In my `import` block (previous message) `[each.key]` refers to the UUID, and the `module.policies` is built on a `.tf` file containg the `resource "jamfpro_policy" "object" {...}` block.
